name: CI/CD Flask -> EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create EKS cluster
        uses: weaveworks/eksctl-action@v5
        with:
          args: |
            create cluster \
            --name flask-eks \
            --version 1.27 \
            --region ${{ secrets.AWS_REGION }} \
            --nodegroup-name linux-nodes \
            --node-type t3.medium \
            --nodes 2 \
            --nodes-min 1 \
            --nodes-max 3 \
            --managed

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      - name: Deploy to EKS
        run: |
          eksctl utils write-kubeconfig --cluster=flask-eks --region=${{ secrets.AWS_REGION }}
          kubectl apply -f k8s/

